# Site settings
title: Adirelle's Den
email: adirelle@gmail.com
description: >
  Le blog d'Adirelle sur Linux, le PHP, l'open-source et l'origine du monde.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://adirelle.github.io"
twitter_username: false
github_username:  Adirelle

# Build settings
markdown: kramdown
source:      .
destination: ./_site
